name: Build and test
on:
  push:
    paths-ignore:
      - '*.md'
  schedule:
    - cron: '25 5 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run all checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
